---
- name: Configure Backup Server
  hosts: backup
  become: yes

  tasks:

  - name: Create backup directory
    file:
     path: /backup
     state: directory
     owner: root
     group: root
     mode: '0755'

  - name: Create timestamped backup
    shell: tar -cvzf /backup/shared-backup-$(date +%F-%H%M).tar.gz /shared
    
